apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: baab-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: name
        image: vchakoshy/baab
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"